name: monocular-depth-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - matplotlib
  - scikit-learn
  - tqdm
  - pip
  - pip:
      - opencv-python
      - timm
      - torch==1.13.1
      - torchvision==0.14.1